# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' calc_roots_from_seeds_C
#' @name calc_roots_from_seeds_C
#' @title calc_roots_from_seeds_C
#' @description Create Student data frame.
#' @param seeds seeds
#' @param roots roots from polynom equation
#' @param poly polynomial coefficients
#' @examples
#' library(Rcpp)
#' df <- expand.grid(re = seq(0,10,0.1), im = seq(-10,0,0.1))
#' seeds <- complex(df$re,df$im)
#' calc_roots_from_seeds_C(seeds, c(0.2,2.5,3+1i), 1:10)
#' @export
NULL

calc_roots_from_seeds_C <- function(seeds, roots, poly) {
    .Call(`_slvwagner_calc_roots_from_seeds_C`, seeds, roots, poly)
}

