# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' math_findNeighbours_2D
#' @name math_findNeighbours_2D
#' @title math_findNeighbours_2D
#' @description checks if all neighbour indices are there to detect an edge.
#' @param c_search flat search vector to create a matrix(c_search,n_row,byrow = T)
#' @param n_col x direction of the matrix
#' @return logical vector if edge was found
#' @examples
#' n_col <- 7
#'  c_flat <- c(
#'   0,1,0,0,0,1,0,
#'   1,1,1,1,1,1,1,
#'   0,1,0,1,1,1,1,
#'   0,0,1,1,1,1,1)
#' m <- c_flat|>
#'   matrix(ncol = n_col, byrow = T)
#' m
#' df_data <- expand.grid(x = 1:n_col,  y = 1:4)
#' df_data$search <- c_flat == T
#' df_data$edge <- math_findNeighbours_2D(c_flat,n_col)
#' df_data$search == math_findNeighbours_2D(c_flat,n_col)
#' plot(df_data$x, df_data$y, col = df_data$search, main = "Search")
#' plot(df_data$x, df_data$y, col = df_data$edge, main = "Edges")
#'
#' @export
NULL

math_findNeighbours_2D <- function(c_search, n_col) {
    .Call(`_slvwagner_math_findNeighbours_2D`, c_search, n_col)
}

#' calc_roots_from_seeds_C
#' @name calc_roots_from_seeds_C
#' @title calc_roots_from_seeds_C
#' @description Create Student data frame.
#' @param seeds seeds
#' @param roots roots from polynom equation
#' @param poly polynomial coefficients
#' @examples
#' library(Rcpp)
#' df <- expand.grid(re = seq(0,10,0.1), im = seq(-10,0,0.1))
#' seeds <- complex(df$re,df$im)
#' calc_roots_from_seeds_C(seeds, c(0.2,2.5,3+1i), 1:10)
#' @export
NULL

#' expandGridComplex
#' @name expandGridComplex
#' @title expandGridComplex
#' @description
#' Create Student data frame with all possible variants of a complex vector.
#' @param x complex vector
#' @param epsilon consider the imaginary value as zero if smaller then \code{epsilon}
#' @return
#' returns a complex vector
#' @examples
#' expandGridComplex(complex(real = 1:100, imag = rnorm(100)))
#' @export
NULL

calc_roots_from_seeds_C <- function(seeds, roots, poly) {
    .Call(`_slvwagner_calc_roots_from_seeds_C`, seeds, roots, poly)
}

expandGridComplex <- function(x, epsilon = 1e-10) {
    .Call(`_slvwagner_expandGridComplex`, x, epsilon)
}

